<style>
    a:link,
    a:visited {
        color: #0398CA;
    }
 
    span#zf-name {
        color: #91BE3F;
    }
 
    div#welcome {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }
 
    div#more-information {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>

<div id="welcome">
<h1>Welcome to Dominik's page</h1>
<h2>Chinas Wirtschaft im Rückwärtsgang</h2>
<div id="more-information">Alle Zinssenkungen und Abwertungen haben bisher offenbar nichts genutzt: Chinas Industrieproduktion ist im August zurückgegangen - das sagt zumindest ein wichtiges Konjunkturbarometer aus. Die Sorgen vor einem abrupten Abbremsen der Konjunktur wachsen. Von Markus Rimmele. [<a>mehr</a>] </div>
</div>