<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN">

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Dominik's Default Application</title>
</head>
<body>
	<h1>An error occured</h1>
	<h2><?php echo $this->message ?></h2>

	<?php if('development' == $this->env) : ?>
	
	<h3>Exception information:</h3>

	<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>
	
	<h3>Stack trace:</h3>
	<pre><?php echo $this->exception->getTraceAsString()?></pre>
	
	<h3>Request Parameters:</h3>
	<pre><?php echo var_export($this->request->getParams(), 1) ?></pre>
	
	<?php endif; ?>
	
	
</body>
</html>